name: deploy blog
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
      - name: Install Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16.20.0'
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: '.output/'
          REMOTE_HOST: '81.68.108.130'
          REMOTE_USER: root
          TARGET: '/home/blog' # 打包后的 dist 文件夹将放在
          # EXCLUDE: "node_modules,.git,.github"
