name: deploy blog
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
      - name: Install Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18.18.1'
      - uses: pnpm/action-setup@v3.0.0
        name: Install pnpm dependencies
        with:
          version: 9.5.0
          run_install: true
      - name: Run build task
        run: pnpm build
      - name: Deploy to tencent cloud server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: '.output/'
          REMOTE_HOST: '62.234.163.223'
          REMOTE_USER: root
          TARGET: '/home/blog' # 打包后的 dist 文件夹将放在
          # EXCLUDE: "node_modules,.git,.github"
      - name: Deploy to aliyun cloud server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: '.output/'
          REMOTE_HOST: '182.92.222.231'
          REMOTE_USER: root
          TARGET: '/home/blog' # 打包后的 dist 文件夹将放在
          # EXCLUDE: "node_modules,.git,.github"
